services:
  traefik:
    image: traefik:v3.4
    environment:
      - DOCKER_API_VERSION=1.54
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - letsencrypt:/letsencrypt
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true

volumes:
  letsencrypt:
